name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Verify:
    uses: ./.github/workflows/verify.yml

  Test:
    needs: Verify
    uses: ./.github/workflows/test.yml

  Build:
    needs: Test
    uses: ./.github/workflows/build.yml
