name: Main

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  build:
    name: Build
    needs: verify
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
