name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: rust:1.75-slim
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y pkg-config libssl-dev
      - run: cargo test

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75
      - run: cargo test

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75
      - run: cargo test
