name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container: rust:1.75-slim
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y pkg-config libssl-dev
      - run: cargo test

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75
      - run: cargo test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75
      - run: cargo test
